apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api-tls
  namespace: default
spec:
  secretName: api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.******
  dnsNames:
  - api.********
  acme:
    config:
    - http01:
        ingress: gke
      domains:
      - api.********
